theme: jekyll-theme-cayman

# Setup

title:        "Encrypter"
tagline:      "Makes sharing secure messages possible"
#baseurl:      ""
#paginate:     0
#locale: "en"

About/contact
author:
name:       Encrypter
url: https://play.google.com/store/apps/details?id=com.halloran.Encrypter

show_downloads: true
